pub mod parse_c;
pub mod parse_json;

use std::fmt::Write as _;

use crate::codes;
use crate::ir::{Key, Keymap};

/// Render a `Keymap` as a QMK Configurator JSON string.
///
/// Unknown keys are left as their ZMK names so the output is still diff-able.
#[must_use]
pub fn render_json(keymap: &Keymap) -> String {
    let keyboard = keymap.keyboard.as_deref().unwrap_or("unknown");
    let layout = keymap.layout.as_deref().unwrap_or("LAYOUT");

    let layers: Vec<Vec<String>> = keymap
        .layers
        .iter()
        .map(|l| l.keys.iter().map(key_to_qmk_str).collect())
        .collect();

    // Build JSON manually to avoid pulling in a serialization derive on the output side.
    let mut out = String::new();
    out.push_str("{\n");
    let _ = writeln!(out, r#"  "version": 1,"#);
    let _ = writeln!(out, r#"  "notes": "Converted from ZMK by zmk2qmk","#);
    let _ = writeln!(out, r#"  "keyboard": "{keyboard}","#);
    let _ = writeln!(out, r#"  "keymap": "converted","#);
    let _ = writeln!(out, r#"  "layout": "{layout}","#);
    out.push_str(r#"  "layers": ["#);
    out.push('\n');

    for (i, layer) in layers.iter().enumerate() {
        out.push_str("    [");
        for (j, key) in layer.iter().enumerate() {
            let _ = write!(out, r#""{key}""#);
            if j + 1 < layer.len() {
                out.push_str(", ");
            }
        }
        out.push(']');
        if i + 1 < layers.len() {
            out.push(',');
        }
        out.push('\n');
    }

    out.push_str("  ]\n}\n");
    out
}

/// Render a `Keymap` as a QMK `keymap.c` source file.
///
/// The LAYOUT macro name defaults to `LAYOUT`; pass a custom name via
/// [`Keymap::layout`] if you know the keyboard's actual macro name.
#[must_use]
pub fn render_c(keymap: &Keymap, cols_override: Option<usize>) -> String {
    let layout = keymap.layout.as_deref().unwrap_or("LAYOUT");
    let mut out = String::new();

    out.push_str("// Generated by zmk2qmk\n");
    out.push_str("// Review and adjust before flashing\n\n");
    out.push_str("#include QMK_KEYBOARD_H\n\n");

    if !keymap.macros.is_empty() {
        render_c_macros(&mut out, keymap);
    }

    // Emit layer enum
    out.push_str("enum layers {\n");
    for layer in &keymap.layers {
        let _ = writeln!(out, "    {},", layer_enum_name(&layer.name));
    }
    out.push_str("};\n\n");

    out.push_str("const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {\n");

    for layer in &keymap.layers {
        let _ = writeln!(out, "    [{}] = {layout}(", layer_enum_name(&layer.name));

        let rendered: Vec<String> = layer.keys.iter().map(key_to_qmk_str).collect();
        let col_width = rendered.iter().map(String::len).max().unwrap_or(6).min(20) + 1;
        let cols = cols_override.unwrap_or_else(|| infer_cols(layer.keys.len()));

        for (i, k) in rendered.iter().enumerate() {
            if i % cols == 0 {
                out.push_str("        ");
            }
            let _ = write!(out, "{k:<col_width$}");
            if i + 1 < rendered.len() {
                out.push(',');
            }
            if (i + 1) % cols == 0 || i + 1 == rendered.len() {
                out.push('\n');
            }
        }

        out.push_str("    ),\n\n");
    }

    out.push_str("};\n");
    out
}

fn render_c_macros(out: &mut String, keymap: &Keymap) {
    out.push_str("bool process_record_user(uint16_t keycode, keyrecord_t *record) {\n");
    out.push_str("    switch (keycode) {\n");
    for m in &keymap.macros {
        let _ = writeln!(out, "        case {}: // TODO: implement macro", m.name);
        out.push_str("            break;\n");
    }
    out.push_str("    }\n");
    out.push_str("    return true;\n");
    out.push_str("}\n\n");
}

fn key_to_qmk_str(key: &Key) -> String {
    match key {
        Key::Trans         => "KC_TRNS".into(),
        Key::None          => "KC_NO".into(),
        Key::CapsWord      => "CW_TOGG".into(),
        Key::Bootloader    => "QK_BOOT".into(),
        Key::SysReset      => "QK_RBT".into(),
        Key::Kp(zmk)       => codes::zmk_key_expr_to_qmk(zmk),
        Key::Mo(n)         => format!("MO({n})"),
        Key::Tog(n)        => format!("TG({n})"),
        Key::Sk(m)         => format!("OSM({})", codes::zmk_mod_to_qmk(m)),
        Key::Sl(n)         => format!("OSL({n})"),
        Key::To(n)         => format!("TO({n})"),
        Key::Df(n)         => format!("DF({n})"),
        Key::Mmv(d)        => zmk_mmv_to_qmk(d),
        Key::Mkp(b)        => zmk_mkp_to_qmk(b),
        Key::Msc(d)        => zmk_msc_to_qmk(d),
        Key::Lt(n, k)      => format!("LT({n},{})", codes::zmk_key_expr_to_qmk(k)),
        Key::Mt(m, k)      => {
            let qm = codes::zmk_mod_to_qmk(m);
            format!("MT({qm},{})", codes::zmk_key_expr_to_qmk(k))
        }
        Key::RgbUg(a)      => codes::zmk_rgb_to_qmk(a)
                                   .map_or_else(|| format!("/* {a} */"), Into::into),
        Key::Macro(name)   => name.clone(),
        Key::Unknown(s)    => format!("/* TODO: {s} */"),
    }
}

fn zmk_mmv_to_qmk(dir: &str) -> String {
    match dir {
        "MOVE_UP"    => "KC_MS_U".into(),
        "MOVE_DOWN"  => "KC_MS_D".into(),
        "MOVE_LEFT"  => "KC_MS_L".into(),
        "MOVE_RIGHT" => "KC_MS_R".into(),
        _ => format!("/* mmv {dir} */"),
    }
}

fn zmk_mkp_to_qmk(btn: &str) -> String {
    match btn {
        "LCLK" => "KC_BTN1".into(),
        "RCLK" => "KC_BTN2".into(),
        "MCLK" => "KC_BTN3".into(),
        "BTN4" => "KC_BTN4".into(),
        "BTN5" => "KC_BTN5".into(),
        _ => format!("/* mkp {btn} */"),
    }
}

fn zmk_msc_to_qmk(dir: &str) -> String {
    match dir {
        "SCRL_UP"    => "KC_WH_U".into(),
        "SCRL_DOWN"  => "KC_WH_D".into(),
        "SCRL_LEFT"  => "KC_WH_L".into(),
        "SCRL_RIGHT" => "KC_WH_R".into(),
        _ => format!("/* msc {dir} */"),
    }
}

fn layer_enum_name(zmk_name: &str) -> String {
    let base = zmk_name
        .trim_end_matches("_layer")
        .trim_start_matches('_');
    if base.is_empty() {
        "_BASE".into()
    } else {
        format!("_{}", base.to_uppercase())
    }
}

fn infer_cols(key_count: usize) -> usize {
    for &cols in &[12usize, 10, 6] {
        if key_count.is_multiple_of(cols) {
            return cols;
        }
    }
    12
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::Layer;

    fn simple_keymap(keys: Vec<Key>) -> Keymap {
        Keymap {
            keyboard: None,
            layout: None,
            layers: vec![Layer { name: "base_layer".into(), index: 0, keys }],
            macros: vec![],
            tri_layer: None,
        }
    }

    #[test]
    fn json_basic_structure() {
        let km = simple_keymap(vec![Key::Kp("Q".into()), Key::Trans]);
        let out = render_json(&km);
        assert!(out.contains(r#""version": 1"#));
        assert!(out.contains(r#""layers""#));
        assert!(out.contains(r#""KC_Q""#));
        assert!(out.contains(r#""KC_TRNS""#));
    }

    #[test]
    fn json_special_keys() {
        let km = simple_keymap(vec![
            Key::None,
            Key::CapsWord,
            Key::Bootloader,
            Key::SysReset,
            Key::Mo(1),
            Key::Tog(2),
        ]);
        let out = render_json(&km);
        assert!(out.contains(r#""KC_NO""#));
        assert!(out.contains(r#""CW_TOGG""#));
        assert!(out.contains(r#""QK_BOOT""#));
        assert!(out.contains(r#""QK_RBT""#));
        assert!(out.contains(r#""MO(1)""#));
        assert!(out.contains(r#""TG(2)""#));
    }

    #[test]
    fn json_one_shot_and_to() {
        let km = simple_keymap(vec![
            Key::Sk("LSHFT".into()),
            Key::Sl(1),
            Key::To(0),
        ]);
        let out = render_json(&km);
        assert!(out.contains(r#""OSM(MOD_LSFT)""#));
        assert!(out.contains(r#""OSL(1)""#));
        assert!(out.contains(r#""TO(0)""#));
    }

    #[test]
    fn json_mouse_keys() {
        let km = simple_keymap(vec![
            Key::Mmv("MOVE_UP".into()),
            Key::Mmv("MOVE_DOWN".into()),
            Key::Mkp("LCLK".into()),
            Key::Mkp("RCLK".into()),
            Key::Msc("SCRL_UP".into()),
            Key::Msc("SCRL_DOWN".into()),
        ]);
        let out = render_json(&km);
        assert!(out.contains(r#""KC_MS_U""#));
        assert!(out.contains(r#""KC_MS_D""#));
        assert!(out.contains(r#""KC_BTN1""#));
        assert!(out.contains(r#""KC_BTN2""#));
        assert!(out.contains(r#""KC_WH_U""#));
        assert!(out.contains(r#""KC_WH_D""#));
    }

    #[test]
    fn json_df_renders_as_df() {
        let km = simple_keymap(vec![Key::Df(1)]);
        let out = render_json(&km);
        assert!(out.contains(r#""DF(1)""#));
    }

    #[test]
    fn json_lt_mt_remapped() {
        let km = simple_keymap(vec![
            Key::Lt(1, "SPACE".into()),
            Key::Mt("LSHFT".into(), "Z".into()),
        ]);
        let out = render_json(&km);
        assert!(out.contains(r#""LT(1,KC_SPACE)""#));
        assert!(out.contains(r#""MT(MOD_LSFT,KC_Z)""#));
    }

    #[test]
    fn c_basic_structure() {
        let km = simple_keymap(vec![Key::Kp("Q".into()), Key::Trans]);
        let out = render_c(&km, None);
        assert!(out.contains("#include QMK_KEYBOARD_H"));
        assert!(out.contains("keymaps[][MATRIX_ROWS][MATRIX_COLS]"));
        assert!(out.contains("LAYOUT("));
        assert!(out.contains("KC_Q"));
        assert!(out.contains("KC_TRNS"));
    }

    #[test]
    fn c_layer_enum() {
        let km = simple_keymap(vec![Key::Trans]);
        let out = render_c(&km, None);
        assert!(out.contains("enum layers"));
        assert!(out.contains("_BASE"));
    }

    #[test]
    fn layer_enum_name_strips_layer_suffix() {
        assert_eq!(layer_enum_name("base_layer"),   "_BASE");
        assert_eq!(layer_enum_name("lower_layer"),  "_LOWER");
        assert_eq!(layer_enum_name("adjust_layer"), "_ADJUST");
        assert_eq!(layer_enum_name("_BASE"),        "_BASE");
    }

    #[test]
    fn modifier_expr_converted() {
        let km = simple_keymap(vec![Key::Kp("LC(C)".into()), Key::Kp("LG(LS(LBKT))".into())]);
        let out = render_json(&km);
        assert!(out.contains(r#""LCTL(KC_C)""#));
        assert!(out.contains(r#""LGUI(LSFT(KC_LBRC))""#));
    }

    #[test]
    fn truly_unknown_zmk_key_rendered_as_raw() {
        let km = simple_keymap(vec![Key::Kp("WEIRD_BEHAVIOR".into())]);
        let out = render_json(&km);
        assert!(out.contains("WEIRD_BEHAVIOR"));
    }
}
