//! QMK renderers and parsers.
//!
//! The `parse_*` submodules translate QMK inputs into the shared IR. The
//! renderers in this module perform the reverse operation, writing either QMK
//! Configurator JSON or a compilable starter `keymap.c`. Unsupported bindings
//! are preserved as comments where possible so users can repair the generated
//! output instead of losing information silently.

pub mod parse_c;
pub mod parse_json;

use std::fmt::Write as _;

use crate::ir::{Key, Keyboard, TapDanceDef};

/// Render a `Keyboard` as a QMK Configurator JSON string.
///
/// The output keeps the original keyboard and layout metadata when the IR has
/// it. Unknown keys are left as their ZMK names so the output is still
/// inspectable and diff-able.
#[must_use]
pub fn render_json(keyboard: &Keyboard) -> String {
    let keyboard_name = keyboard.keyboard.as_deref().unwrap_or("unknown");
    let layout = keyboard.layout.as_deref().unwrap_or("LAYOUT");

    let tap_dances = &keyboard.tap_dances;
    let layers: Vec<Vec<String>> = keyboard
        .layers
        .iter()
        .map(|l| {
            l.keys
                .iter()
                .map(|k| key_to_qmk_str(k, tap_dances))
                .collect()
        })
        .collect();

    // Build JSON manually to avoid pulling in a serialization derive on the output side.
    let mut out = String::new();
    out.push_str("{\n");
    let _ = writeln!(out, r#"  "version": 1,"#);
    let _ = writeln!(out, r#"  "notes": "Converted from ZMK by zmk2qmk","#);
    let _ = writeln!(out, r#"  "keyboard": "{keyboard_name}","#);
    let _ = writeln!(out, r#"  "keymap": "converted","#);
    let _ = writeln!(out, r#"  "layout": "{layout}","#);
    out.push_str(r#"  "layers": ["#);
    out.push('\n');

    for (i, layer) in layers.iter().enumerate() {
        out.push_str("    [");
        for (j, key) in layer.iter().enumerate() {
            let _ = write!(out, r#""{key}""#);
            if j + 1 < layer.len() {
                out.push_str(", ");
            }
        }
        out.push(']');
        if i + 1 < layers.len() {
            out.push(',');
        }
        out.push('\n');
    }

    out.push_str("  ]\n}\n");
    out
}

/// Render a `Keyboard` as a QMK `keymap.c` source file.
///
/// The LAYOUT macro name defaults to `LAYOUT`; pass a custom name via
/// [`Keyboard::layout`] if you know the keyboard's actual macro name. Column
/// layout is for readability only; QMK ultimately consumes the flat argument
/// list inside the selected layout macro.
#[must_use]
pub fn render_c(keyboard: &Keyboard, cols_override: Option<usize>) -> String {
    let layout = keyboard.layout.as_deref().unwrap_or("LAYOUT");
    let mut out = String::new();

    out.push_str("// Generated by zmk2qmk\n");
    out.push_str("// Review and adjust before flashing\n\n");
    out.push_str("#include QMK_KEYBOARD_H\n\n");

    if !keyboard.tap_dances.is_empty() {
        render_c_tap_dances(&mut out, keyboard);
    }

    if !keyboard.macros.is_empty() {
        render_c_macros(&mut out, keyboard);
    }

    // Emit layer enum
    out.push_str("enum layers {\n");
    for layer in &keyboard.layers {
        let _ = writeln!(out, "    {},", layer_enum_name(&layer.name));
    }
    out.push_str("};\n\n");

    out.push_str("const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {\n");

    for layer in &keyboard.layers {
        let _ = writeln!(out, "    [{}] = {layout}(", layer_enum_name(&layer.name));

        let rendered: Vec<String> = layer
            .keys
            .iter()
            .map(|k| key_to_qmk_str(k, &keyboard.tap_dances))
            .collect();
        let col_width = rendered.iter().map(String::len).max().unwrap_or(6).min(20) + 1;
        let cols = cols_override.unwrap_or_else(|| infer_cols(layer.keys.len()));

        for (i, k) in rendered.iter().enumerate() {
            if i % cols == 0 {
                out.push_str("        ");
            }
            let _ = write!(out, "{k:<col_width$}");
            if i + 1 < rendered.len() {
                out.push(',');
            }
            if (i + 1) % cols == 0 || i + 1 == rendered.len() {
                out.push('\n');
            }
        }

        out.push_str("    ),\n\n");
    }

    out.push_str("};\n");
    out
}

fn render_c_macros(out: &mut String, keyboard: &Keyboard) {
    out.push_str("bool process_record_user(uint16_t keycode, keyrecord_t *record) {\n");
    out.push_str("    switch (keycode) {\n");
    for m in &keyboard.macros {
        let _ = writeln!(out, "        case {}: // TODO: implement macro", m.name);
        out.push_str("            break;\n");
    }
    out.push_str("    }\n");
    out.push_str("    return true;\n");
    out.push_str("}\n\n");
}

/// Render one IR key as a QMK keycode or key expression.
///
/// Unsupported or lossy bindings are emitted as C comments so the generated file
/// remains reviewable and does not silently replace behavior with `KC_NO`.
fn key_to_qmk_str(key: &Key, tap_dances: &[TapDanceDef]) -> String {
    match key {
        Key::Trans => "KC_TRNS".into(),
        Key::None => "KC_NO".into(),
        Key::CapsWord => "CW_TOGG".into(),
        Key::Bootloader => "QK_BOOT".into(),
        Key::SysReset => "QK_RBT".into(),
        Key::Kp(key) => key.to_qmk(),
        Key::Mo(n) => format!("MO({n})"),
        Key::Tog(n) => format!("TG({n})"),
        Key::Sk(m) => format!("OSM({})", m.qmk_mod_name()),
        Key::Sl(n) => format!("OSL({n})"),
        Key::To(n) => format!("TO({n})"),
        Key::Df(n) => format!("DF({n})"),
        Key::Mmv(d) => d.qmk_name().to_string(),
        Key::Mkp(b) => b.qmk_name().to_string(),
        Key::Msc(d) => d.qmk_name().to_string(),
        Key::Lt(n, k) => format!("LT({n},{})", k.to_qmk()),
        Key::Mt(m, k) => format!("MT({},{})", m.qmk_mod_name(), k.to_qmk()),
        Key::RgbUg(a) => a.qmk_name().to_string(),
        Key::Macro(name) => name.clone(),
        Key::TapDance(n) => tap_dances.get(*n).map_or_else(
            || format!("TD(DANCE_{n})"),
            |td| format!("TD({})", td.name.to_uppercase()),
        ),
        Key::Unknown(s) => format!("/* TODO: {s} */"),
    }
}

/// Emit QMK tap-dance declarations for tap-dance definitions in the IR.
///
/// Two-binding tap dances can use QMK's simple double-tap helper. More complex
/// definitions need user code, so the renderer emits an advanced action stub.
fn render_c_tap_dances(out: &mut String, keyboard: &Keyboard) {
    out.push_str("enum tap_dance_codes {\n");
    for td in &keyboard.tap_dances {
        let _ = writeln!(out, "    {},", td.name.to_uppercase());
    }
    out.push_str("};\n\n");

    out.push_str("tap_dance_action_t tap_dance_actions[] = {\n");
    for td in &keyboard.tap_dances {
        let action = if td.bindings.len() == 2 {
            let kc1 = key_to_qmk_str(&td.bindings[0], &[]);
            let kc2 = key_to_qmk_str(&td.bindings[1], &[]);
            format!("ACTION_TAP_DANCE_DOUBLE({kc1}, {kc2})")
        } else {
            "ACTION_TAP_DANCE_FN_ADVANCED(NULL, NULL, NULL) /* TODO: fill in */".to_string()
        };
        let _ = writeln!(out, "    [{}] = {action},", td.name.to_uppercase());
    }
    out.push_str("};\n\n");
}

/// Convert a ZMK layer node name into a conventional QMK layer enum variant.
///
/// ZMK commonly uses names like `base_layer`; QMK examples commonly use
/// `_BASE`. Empty names fall back to `_BASE`.
fn layer_enum_name(zmk_name: &str) -> String {
    let base = zmk_name.trim_end_matches("_layer").trim_start_matches('_');
    if base.is_empty() {
        "_BASE".into()
    } else {
        format!("_{}", base.to_uppercase())
    }
}

/// Pick a readable default column count from the total number of keys.
fn infer_cols(key_count: usize) -> usize {
    for &cols in &[12usize, 10, 6] {
        if key_count.is_multiple_of(cols) {
            return cols;
        }
    }
    12
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::Layer;

    fn simple_keymap(keys: Vec<Key>) -> Keyboard {
        Keyboard {
            keyboard: None,
            layout: None,
            layers: vec![Layer {
                name: "base_layer".into(),
                index: 0,
                keys,
            }],
            macros: vec![],
            tap_dances: vec![],
            tri_layer: None,
        }
    }

    #[test]
    fn json_basic_structure() {
        let km = simple_keymap(vec![Key::Kp("Q".into()), Key::Trans]);
        let out = render_json(&km);
        assert!(out.contains(r#""version": 1"#));
        assert!(out.contains(r#""layers""#));
        assert!(out.contains(r#""KC_Q""#));
        assert!(out.contains(r#""KC_TRNS""#));
    }

    #[test]
    fn json_special_keys() {
        let km = simple_keymap(vec![
            Key::None,
            Key::CapsWord,
            Key::Bootloader,
            Key::SysReset,
            Key::Mo(1),
            Key::Tog(2),
        ]);
        let out = render_json(&km);
        assert!(out.contains(r#""KC_NO""#));
        assert!(out.contains(r#""CW_TOGG""#));
        assert!(out.contains(r#""QK_BOOT""#));
        assert!(out.contains(r#""QK_RBT""#));
        assert!(out.contains(r#""MO(1)""#));
        assert!(out.contains(r#""TG(2)""#));
    }

    #[test]
    fn json_one_shot_and_to() {
        let km = simple_keymap(vec![Key::Sk("LSHFT".into()), Key::Sl(1), Key::To(0)]);
        let out = render_json(&km);
        assert!(out.contains(r#""OSM(MOD_LSFT)""#));
        assert!(out.contains(r#""OSL(1)""#));
        assert!(out.contains(r#""TO(0)""#));
    }

    #[test]
    fn json_mouse_keys() {
        let km = simple_keymap(vec![
            Key::Mmv("MOVE_UP".into()),
            Key::Mmv("MOVE_DOWN".into()),
            Key::Mkp("LCLK".into()),
            Key::Mkp("RCLK".into()),
            Key::Msc("SCRL_UP".into()),
            Key::Msc("SCRL_DOWN".into()),
        ]);
        let out = render_json(&km);
        assert!(out.contains(r#""KC_MS_U""#));
        assert!(out.contains(r#""KC_MS_D""#));
        assert!(out.contains(r#""KC_BTN1""#));
        assert!(out.contains(r#""KC_BTN2""#));
        assert!(out.contains(r#""KC_WH_U""#));
        assert!(out.contains(r#""KC_WH_D""#));
    }

    #[test]
    fn json_df_renders_as_df() {
        let km = simple_keymap(vec![Key::Df(1)]);
        let out = render_json(&km);
        assert!(out.contains(r#""DF(1)""#));
    }

    #[test]
    fn json_lt_mt_remapped() {
        let km = simple_keymap(vec![
            Key::Lt(1, "SPACE".into()),
            Key::Mt("LSHFT".into(), "Z".into()),
        ]);
        let out = render_json(&km);
        assert!(out.contains(r#""LT(1,KC_SPACE)""#));
        assert!(out.contains(r#""MT(MOD_LSFT,KC_Z)""#));
    }

    #[test]
    fn c_basic_structure() {
        let km = simple_keymap(vec![Key::Kp("Q".into()), Key::Trans]);
        let out = render_c(&km, None);
        assert!(out.contains("#include QMK_KEYBOARD_H"));
        assert!(out.contains("keymaps[][MATRIX_ROWS][MATRIX_COLS]"));
        assert!(out.contains("LAYOUT("));
        assert!(out.contains("KC_Q"));
        assert!(out.contains("KC_TRNS"));
    }

    #[test]
    fn c_layer_enum() {
        let km = simple_keymap(vec![Key::Trans]);
        let out = render_c(&km, None);
        assert!(out.contains("enum layers"));
        assert!(out.contains("_BASE"));
    }

    #[test]
    fn layer_enum_name_strips_layer_suffix() {
        assert_eq!(layer_enum_name("base_layer"), "_BASE");
        assert_eq!(layer_enum_name("lower_layer"), "_LOWER");
        assert_eq!(layer_enum_name("adjust_layer"), "_ADJUST");
        assert_eq!(layer_enum_name("_BASE"), "_BASE");
    }

    #[test]
    fn modifier_expr_converted() {
        let km = simple_keymap(vec![
            Key::Kp("LC(C)".into()),
            Key::Kp("LG(LS(LBKT))".into()),
        ]);
        let out = render_json(&km);
        assert!(out.contains(r#""LCTL(KC_C)""#));
        assert!(out.contains(r#""LGUI(LSFT(KC_LBRC))""#));
    }

    #[test]
    fn truly_unknown_zmk_key_rendered_as_raw() {
        let km = simple_keymap(vec![Key::Kp("WEIRD_BEHAVIOR".into())]);
        let out = render_json(&km);
        assert!(out.contains("WEIRD_BEHAVIOR"));
    }

    #[test]
    fn tap_dance_renders_with_name_in_json() {
        use crate::ir::TapDanceDef;
        let mut km = simple_keymap(vec![Key::TapDance(0)]);
        km.tap_dances = vec![TapDanceDef {
            name: "dance_0".into(),
            bindings: vec![Key::Kp("LSHFT".into()), Key::Kp("CAPS".into())],
        }];
        let out = render_json(&km);
        assert!(out.contains(r#""TD(DANCE_0)""#));
    }

    #[test]
    fn tap_dance_fallback_when_index_out_of_range() {
        let km = simple_keymap(vec![Key::TapDance(5)]);
        let out = render_json(&km);
        assert!(out.contains(r#""TD(DANCE_5)""#));
    }

    #[test]
    fn c_tap_dance_block_emitted() {
        use crate::ir::TapDanceDef;
        let mut km = simple_keymap(vec![Key::TapDance(0)]);
        km.tap_dances = vec![TapDanceDef {
            name: "dance_0".into(),
            bindings: vec![Key::Kp("LSHFT".into()), Key::Kp("CAPS".into())],
        }];
        let out = render_c(&km, None);
        assert!(out.contains("enum tap_dance_codes"));
        assert!(out.contains("DANCE_0,"));
        assert!(out.contains("tap_dance_actions[]"));
        assert!(out.contains("ACTION_TAP_DANCE_DOUBLE(KC_LSFT, KC_CAPS)"));
        assert!(out.contains("TD(DANCE_0)"));
    }

    #[test]
    fn c_tap_dance_fn_advanced_stub_for_other_counts() {
        use crate::ir::TapDanceDef;
        let mut km = simple_keymap(vec![Key::TapDance(0)]);
        km.tap_dances = vec![TapDanceDef {
            name: "dance_0".into(),
            bindings: vec![
                Key::Kp("A".into()),
                Key::Kp("B".into()),
                Key::Kp("C".into()),
            ],
        }];
        let out = render_c(&km, None);
        assert!(out.contains("ACTION_TAP_DANCE_FN_ADVANCED"));
        assert!(out.contains("TODO"));
    }
}
