//! ZMK renderer and parser.
//!
//! Rendering turns the shared IR into a `.keymap` DTS overlay with only the
//! includes and behavior blocks needed by the current keymap. Parsing performs
//! the reverse operation in [`parse`], preserving unsupported bindings as
//! [`crate::ir::Key::Unknown`] so conversion can continue.

pub mod parse;

use std::collections::HashSet;
use std::fmt::Write as _;

use crate::codes;
use crate::ir::{Key, Keyboard, Layer, MacroStep, TriLayer};

/// Render a [`Keyboard`] as a ZMK `.keymap` DTS overlay.
///
/// The renderer emits conditional layers, tap dances, macros, and optional RGB
/// or mouse includes only when the IR contains those features. `cols` controls
/// line wrapping of the bindings for readability; it does not change the keymap
/// semantics.
#[must_use]
pub fn render(keyboard: &Keyboard, cols: Option<usize>) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by qmk2zmk\n");
    out.push_str("// Review and adjust before flashing\n\n");

    out.push_str("#include <behaviors.dtsi>\n");
    out.push_str("#include <dt-bindings/zmk/keys.h>\n");

    if uses_rgb(keyboard) {
        out.push_str("#include <dt-bindings/zmk/rgb.h>\n");
    }
    if uses_mouse(keyboard) {
        out.push_str("#include <dt-bindings/zmk/mouse.h>\n");
    }

    out.push_str("\n/ {\n");

    if let Some(tri) = &keyboard.tri_layer {
        render_conditional_layers(&mut out, tri);
    }

    if has_tap_dances(keyboard) {
        render_behaviors(&mut out, keyboard);
    }

    if has_macros(keyboard) {
        render_macros(&mut out, keyboard);
    }

    render_keymap(&mut out, keyboard, cols);

    out.push_str("};\n");
    out
}

/// Render a ZMK shield `.conf` file with `CONFIG_*` flags detected from the IR.
///
/// The returned string always contains the file header comments. Feature flags
/// are added for RGB underglow, pointing / mouse support, and rotary encoders
/// when those features are present in the keymap.
#[must_use]
pub fn render_conf(keyboard: &Keyboard) -> String {
    let mut out = String::from("# Auto-generated by qmk2zmk\n# Review and adjust before flashing\n");
    if uses_rgb(keyboard) {
        out.push_str("CONFIG_ZMK_RGB_UNDERGLOW=y\n");
    }
    if uses_mouse(keyboard) {
        out.push_str("CONFIG_ZMK_POINTING=y\n");
    }
    if uses_encoders(keyboard) {
        out.push_str("CONFIG_EC11=y\n");
        out.push_str("CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y\n");
    }
    out
}

fn render_conditional_layers(out: &mut String, tri: &TriLayer) {
    out.push_str("    conditional_layers {\n");
    out.push_str("        compatible = \"zmk,conditional-layers\";\n");
    out.push_str("        tri_layer {\n");
    let _ = writeln!(
        out,
        "            if-layers = <{} {}>;",
        tri.lower, tri.upper
    );
    let _ = writeln!(out, "            then-layer = <{}>;", tri.tri);
    out.push_str("        };\n");
    out.push_str("    };\n\n");
}

/// Emit ZMK macro behavior nodes.
///
/// Fully parsed macros use their recorded steps. Macro references without a
/// parsed definition still get a stub so layer bindings have a target node the
/// user can fill in.
fn render_macros(out: &mut String, keyboard: &Keyboard) {
    out.push_str("    macros {\n");

    // Emit fully defined macros
    for m in &keyboard.macros {
        let _ = writeln!(out, "        {}: {} {{", m.name, m.name);
        out.push_str("            compatible = \"zmk,behavior-macro\";\n");
        out.push_str("            #binding-cells = <0>;\n");
        if m.steps.is_empty() {
            out.push_str("            // TODO: fill in macro steps\n");
            out.push_str("            bindings = <&none>;\n");
        } else {
            let steps: Vec<String> = m
                .steps
                .iter()
                .map(|s| match s {
                    MacroStep::Tap(k) => format!("<&kp {k}>"),
                    MacroStep::Wait(ms) => format!("<&macro_wait_time {ms}>"),
                })
                .collect();
            let _ = writeln!(out, "            bindings = {};", steps.join(", "));
        }
        out.push_str("        };\n");
    }

    // Emit stubs for referenced macros that weren't fully parsed
    let defined: HashSet<_> = keyboard.macros.iter().map(|m| m.name.as_str()).collect();
    let mut seen: HashSet<String> = HashSet::new();
    for layer in &keyboard.layers {
        for key in &layer.keys {
            let Key::Macro(name) = key else { continue };
            if !defined.contains(name.as_str()) && seen.insert(name.clone()) {
                let _ = writeln!(out, "        {name}: {name} {{");
                out.push_str("            compatible = \"zmk,behavior-macro\";\n");
                out.push_str("            #binding-cells = <0>;\n");
                out.push_str("            // TODO: fill in macro steps\n");
                out.push_str("            bindings = <&none>;\n");
                out.push_str("        };\n");
            }
        }
    }

    out.push_str("    };\n\n");
}

/// Emit the ZMK `keymap` node and all layer binding lists.
///
/// Bindings are padded into columns for readability. The column count does not
/// affect generated DTS semantics.
fn render_keymap(out: &mut String, keyboard: &Keyboard, cols_override: Option<usize>) {
    out.push_str("    keymap {\n");
    out.push_str("        compatible = \"zmk,keymap\";\n\n");

    let cols = infer_cols(keyboard, cols_override);

    for layer in &keyboard.layers {
        let label = layer_label(&layer.name);
        let _ = writeln!(out, "        {label} {{");
        out.push_str("            bindings = <\n");

        // Compute column width for alignment, ignoring TODO comments
        let rendered: Vec<String> = layer.keys.iter().map(render_key).collect();
        let col_width = rendered
            .iter()
            .filter(|s| !s.starts_with("/*"))
            .map(std::string::String::len)
            .max()
            .unwrap_or(6)
            .min(28)
            + 1;

        for (i, binding) in rendered.iter().enumerate() {
            if i % cols == 0 {
                out.push_str("               ");
            }
            let _ = write!(out, "{binding:<col_width$}");
            if (i + 1) % cols == 0 || i + 1 == rendered.len() {
                out.push('\n');
            }
        }

        out.push_str("            >;\n");
        render_sensor_bindings(out, layer);
        out.push_str("        };\n\n");
    }

    out.push_str("    };\n");
}

/// Emit `sensor-bindings` for a layer when encoder pairs are present.
fn render_sensor_bindings(out: &mut String, layer: &Layer) {
    if layer.sensor_bindings.is_empty() {
        return;
    }
    let entries: Vec<String> = layer
        .sensor_bindings
        .iter()
        .map(|(cw, ccw)| format!("<&inc_dec_kp {cw} {ccw}>"))
        .collect();
    let _ = writeln!(out, "            sensor-bindings = {};", entries.join(", "));
}

/// Render one IR key as a ZMK behavior binding.
fn render_key(key: &Key) -> String {
    match key {
        Key::Kp(k) => format!("&kp {k}"),
        Key::Mo(n) => format!("&mo {n}"),
        Key::Lt(n, k) => format!("&lt {n} {k}"),
        Key::Mt(m, k) => format!("&mt {m} {k}"),
        Key::Tog(n) => format!("&tog {n}"),
        Key::Sk(m) => format!("&sk {m}"),
        Key::Sl(n) => format!("&sl {n}"),
        Key::To(n) | Key::Df(n) => format!("&to {n}"),
        Key::Mmv(d) => format!("&mmv {d}"),
        Key::Mkp(b) => format!("&mkp {b}"),
        Key::Msc(d) => format!("&msc {d}"),
        Key::Trans => "&trans".into(),
        Key::None => "&none".into(),
        Key::CapsWord => "&caps_word".into(),
        Key::Bootloader => "&bootloader".into(),
        Key::SysReset => "&sys_reset".into(),
        Key::RgbUg(a) => format!("&rgb_ug {a}"),
        Key::Macro(name) => format!("&{name}"),
        Key::TapDance(n) => format!("&td{n}"),
        Key::Unknown(s) => format!("/* TODO: {s} */"),
    }
}

/// Emit ZMK tap-dance behavior nodes for every tap dance in the IR.
fn render_behaviors(out: &mut String, keyboard: &Keyboard) {
    out.push_str("    behaviors {\n");
    for (i, td) in keyboard.tap_dances.iter().enumerate() {
        let _ = writeln!(out, "        td{i}: tap_dance_{i} {{");
        out.push_str("            compatible = \"zmk,behavior-tap-dance\";\n");
        out.push_str("            #binding-cells = <0>;\n");
        out.push_str("            tapping-term-ms = <200>;\n");
        if td.bindings.is_empty() {
            out.push_str("            // TODO: fill in tap dance bindings\n");
            out.push_str("            bindings = <&trans>;\n");
        } else {
            let binding_strs: Vec<String> = td
                .bindings
                .iter()
                .map(|k| format!("<{}>", render_key(k)))
                .collect();
            let _ = writeln!(out, "            bindings = {};", binding_strs.join(", "));
        }
        out.push_str("        };\n");
    }
    out.push_str("    };\n\n");
}

/// Return whether the output needs a `behaviors` block for tap dances.
fn has_tap_dances(keyboard: &Keyboard) -> bool {
    !keyboard.tap_dances.is_empty()
}

/// Convert a source layer name into a ZMK layer node label.
///
/// QMK-style `_BASE` becomes `base_layer`; names already ending in `_layer` keep
/// that suffix instead of receiving it twice.
fn layer_label(name: &str) -> String {
    let base = name
        .trim_start_matches('_')
        .trim_end_matches("_layer")
        .to_lowercase();
    if base.is_empty() {
        "default_layer".into()
    } else {
        format!("{base}_layer")
    }
}

/// Choose the binding wrap width for rendered ZMK layers.
///
/// Explicit CLI input wins, then known keyboard/layout names, then a simple
/// divisibility heuristic based on the first layer's key count.
fn infer_cols(keyboard: &Keyboard, override_cols: Option<usize>) -> usize {
    if let Some(n) = override_cols {
        return n;
    }
    if let Some(layout) = &keyboard.layout
        && let Some(n) = codes::keyboard_cols(layout)
    {
        return n;
    }
    for &cols in &[12usize, 10, 6] {
        if keyboard
            .layers
            .first()
            .is_some_and(|l| l.keys.len() % cols == 0)
        {
            return cols;
        }
    }
    12
}

/// Return whether any binding requires ZMK RGB binding definitions.
fn uses_rgb(keyboard: &Keyboard) -> bool {
    keyboard
        .layers
        .iter()
        .flat_map(|l| &l.keys)
        .any(|k| matches!(k, Key::RgbUg(_)))
}

/// Return whether any binding requires ZMK mouse binding definitions.
fn uses_mouse(keyboard: &Keyboard) -> bool {
    keyboard
        .layers
        .iter()
        .flat_map(|l| &l.keys)
        .any(|k| matches!(k, Key::Mmv(_) | Key::Mkp(_) | Key::Msc(_)))
}

/// Return whether any layer has encoder sensor bindings.
fn uses_encoders(keyboard: &Keyboard) -> bool {
    keyboard.layers.iter().any(|l| !l.sensor_bindings.is_empty())
}

/// Return whether the output needs a top-level ZMK `macros` block.
fn has_macros(keyboard: &Keyboard) -> bool {
    !keyboard.macros.is_empty()
        || keyboard
            .layers
            .iter()
            .flat_map(|l| &l.keys)
            .any(|k| matches!(k, Key::Macro(_)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::Layer;

    fn simple_keymap(keys: Vec<Key>) -> Keyboard {
        Keyboard {
            keyboard: None,
            layout: None,
            layers: vec![Layer {
                name: "_BASE".into(),
                index: 0,
                keys,
                sensor_bindings: vec![],
            }],
            macros: vec![],
            tap_dances: vec![],
            tri_layer: None,
        }
    }

    #[test]
    fn render_key_basic() {
        assert_eq!(render_key(&Key::Kp("TAB".into())), "&kp TAB");
        assert_eq!(render_key(&Key::Trans), "&trans");
        assert_eq!(render_key(&Key::None), "&none");
        assert_eq!(render_key(&Key::CapsWord), "&caps_word");
        assert_eq!(render_key(&Key::Bootloader), "&bootloader");
        assert_eq!(render_key(&Key::SysReset), "&sys_reset");
    }

    #[test]
    fn render_key_behaviors() {
        assert_eq!(render_key(&Key::Mo(1)), "&mo 1");
        assert_eq!(render_key(&Key::Tog(2)), "&tog 2");
        assert_eq!(render_key(&Key::Sk("LSHFT".into())), "&sk LSHFT");
        assert_eq!(render_key(&Key::Sl(1)), "&sl 1");
        assert_eq!(render_key(&Key::To(0)), "&to 0");
        assert_eq!(render_key(&Key::Df(1)), "&to 1");
        assert_eq!(render_key(&Key::Mmv("MOVE_UP".into())), "&mmv MOVE_UP");
        assert_eq!(render_key(&Key::Mkp("LCLK".into())), "&mkp LCLK");
        assert_eq!(render_key(&Key::Msc("SCRL_UP".into())), "&msc SCRL_UP");
        assert_eq!(
            render_key(&Key::Mt("LALT".into(), "Z".into())),
            "&mt LALT Z"
        );
        assert_eq!(render_key(&Key::Lt(1, "SPACE".into())), "&lt 1 SPACE");
        assert_eq!(render_key(&Key::RgbUg("RGB_TOG".into())), "&rgb_ug RGB_TOG");
        assert_eq!(render_key(&Key::Macro("MY_MACRO".into())), "&MY_MACRO");
    }

    #[test]
    fn mouse_include_only_when_needed() {
        let without = simple_keymap(vec![Key::Kp("A".into())]);
        assert!(!render(&without, None).contains("zmk/mouse.h"));

        let with_mmv = simple_keymap(vec![Key::Mmv("MOVE_UP".into())]);
        assert!(render(&with_mmv, None).contains("zmk/mouse.h"));

        let with_mkp = simple_keymap(vec![Key::Mkp("LCLK".into())]);
        assert!(render(&with_mkp, None).contains("zmk/mouse.h"));
    }

    #[test]
    fn render_key_unknown() {
        let out = render_key(&Key::Unknown("WEIRD_KEY".into()));
        assert!(out.contains("WEIRD_KEY"));
        assert!(out.starts_with("/*"));
    }

    #[test]
    fn layer_label_strips_underscore() {
        assert_eq!(layer_label("_BASE"), "base_layer");
        assert_eq!(layer_label("_LOWER"), "lower_layer");
        assert_eq!(layer_label("_ADJUST"), "adjust_layer");
        assert_eq!(layer_label("QWERTY"), "qwerty_layer");
        assert_eq!(layer_label(""), "default_layer");
        // Round-trip: names already ending in _layer should not double it
        assert_eq!(layer_label("base_layer"), "base_layer");
        assert_eq!(layer_label("lower_layer"), "lower_layer");
        assert_eq!(layer_label("adjust_layer"), "adjust_layer");
    }

    #[test]
    fn output_includes_zmk_header() {
        let km = simple_keymap(vec![Key::Kp("A".into())]);
        let out = render(&km, None);
        assert!(out.contains("#include <behaviors.dtsi>"));
        assert!(out.contains("#include <dt-bindings/zmk/keys.h>"));
    }

    #[test]
    fn rgb_include_only_when_needed() {
        let without_rgb = simple_keymap(vec![Key::Kp("A".into())]);
        assert!(!render(&without_rgb, None).contains("zmk/rgb.h"));

        let with_rgb = simple_keymap(vec![Key::RgbUg("RGB_TOG".into())]);
        assert!(render(&with_rgb, None).contains("zmk/rgb.h"));
    }

    #[test]
    fn conditional_layers_block_emitted() {
        let mut km = simple_keymap(vec![Key::Trans]);
        km.tri_layer = Some(TriLayer {
            lower: 1,
            upper: 2,
            tri: 3,
        });
        let out = render(&km, None);
        assert!(out.contains("conditional_layers"));
        assert!(out.contains("if-layers = <1 2>"));
        assert!(out.contains("then-layer = <3>"));
    }

    #[test]
    fn macro_stub_emitted_for_referenced_macro() {
        let km = simple_keymap(vec![Key::Macro("MY_MACRO".into())]);
        let out = render(&km, None);
        assert!(out.contains("MY_MACRO: MY_MACRO"));
        assert!(out.contains("zmk,behavior-macro"));
        assert!(out.contains("TODO"));
    }

    #[test]
    fn no_macros_block_when_unused() {
        let km = simple_keymap(vec![Key::Kp("A".into()), Key::Trans]);
        let out = render(&km, None);
        assert!(!out.contains("macros {"));
    }

    #[test]
    fn layer_bindings_present() {
        let km = simple_keymap(vec![Key::Kp("TAB".into()), Key::Trans, Key::Mo(1)]);
        let out = render(&km, None);
        assert!(out.contains("base_layer"));
        assert!(out.contains("bindings = <"));
        assert!(out.contains("&kp TAB"));
        assert!(out.contains("&trans"));
        assert!(out.contains("&mo 1"));
    }

    #[test]
    fn infer_cols_from_layout_name() {
        let mut km = simple_keymap(vec![Key::Trans; 48]);
        km.layout = Some("LAYOUT_planck_grid".into());
        assert_eq!(infer_cols(&km, None), 12);

        km.layout = Some("LAYOUT_crkbd_base".into());
        assert_eq!(infer_cols(&km, None), 6);
    }

    #[test]
    fn render_key_tap_dance() {
        assert_eq!(render_key(&Key::TapDance(0)), "&td0");
        assert_eq!(render_key(&Key::TapDance(3)), "&td3");
    }

    #[test]
    fn behaviors_block_emitted_for_tap_dance() {
        use crate::ir::TapDanceDef;
        let mut km = simple_keymap(vec![Key::TapDance(0)]);
        km.tap_dances = vec![TapDanceDef {
            name: "td0".into(),
            bindings: vec![Key::Kp("LSHFT".into()), Key::Kp("CAPS".into())],
        }];
        let out = render(&km, None);
        assert!(out.contains("behaviors {"));
        assert!(out.contains("zmk,behavior-tap-dance"));
        assert!(out.contains("td0: tap_dance_0"));
        assert!(out.contains("<&kp LSHFT>, <&kp CAPS>"));
        assert!(out.contains("&td0"));
    }

    #[test]
    fn behaviors_block_stub_for_empty_bindings() {
        use crate::ir::TapDanceDef;
        let mut km = simple_keymap(vec![Key::TapDance(0)]);
        km.tap_dances = vec![TapDanceDef {
            name: "td0".into(),
            bindings: vec![],
        }];
        let out = render(&km, None);
        assert!(out.contains("TODO"));
        assert!(out.contains("bindings = <&trans>"));
    }

    #[test]
    fn no_behaviors_block_without_tap_dances() {
        let km = simple_keymap(vec![Key::Kp("A".into())]);
        assert!(!render(&km, None).contains("behaviors {"));
    }

    // ── sensor-bindings rendering ─────────────────────────────────────────────

    #[test]
    fn sensor_bindings_emitted_when_present() {
        let mut km = simple_keymap(vec![Key::Kp("A".into())]);
        km.layers[0].sensor_bindings = vec![("C_VOL_UP".into(), "C_VOL_DN".into())];
        let out = render(&km, None);
        assert!(out.contains("sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>;"));
    }

    #[test]
    fn sensor_bindings_absent_when_empty() {
        let km = simple_keymap(vec![Key::Kp("A".into())]);
        assert!(!render(&km, None).contains("sensor-bindings"));
    }

    #[test]
    fn sensor_bindings_multiple_encoders() {
        let mut km = simple_keymap(vec![Key::Trans]);
        km.layers[0].sensor_bindings = vec![
            ("C_VOL_UP".into(), "C_VOL_DN".into()),
            ("PG_DN".into(), "PG_UP".into()),
        ];
        let out = render(&km, None);
        assert!(out.contains(
            "sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>, <&inc_dec_kp PG_DN PG_UP>;"
        ));
    }

    // ── render_conf ───────────────────────────────────────────────────────────

    #[test]
    fn conf_header_always_present() {
        let km = simple_keymap(vec![Key::Kp("A".into())]);
        let conf = render_conf(&km);
        assert!(conf.contains("Auto-generated by qmk2zmk"));
    }

    #[test]
    fn conf_rgb_flag_when_rgb_present() {
        let km = simple_keymap(vec![Key::RgbUg("RGB_TOG".into())]);
        let conf = render_conf(&km);
        assert!(conf.contains("CONFIG_ZMK_RGB_UNDERGLOW=y"));
        assert!(!conf.contains("CONFIG_ZMK_POINTING"));
    }

    #[test]
    fn conf_mouse_flag_when_mouse_present() {
        let km = simple_keymap(vec![Key::Mkp("LCLK".into())]);
        let conf = render_conf(&km);
        assert!(conf.contains("CONFIG_ZMK_POINTING=y"));
        assert!(!conf.contains("CONFIG_ZMK_RGB"));
    }

    #[test]
    fn conf_encoder_flags_when_sensor_bindings_present() {
        let mut km = simple_keymap(vec![Key::Kp("A".into())]);
        km.layers[0].sensor_bindings = vec![("C_VOL_UP".into(), "C_VOL_DN".into())];
        let conf = render_conf(&km);
        assert!(conf.contains("CONFIG_EC11=y"));
        assert!(conf.contains("CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y"));
    }

    #[test]
    fn conf_no_feature_flags_for_plain_keymap() {
        let km = simple_keymap(vec![Key::Kp("A".into()), Key::Trans]);
        let conf = render_conf(&km);
        assert!(!conf.contains("CONFIG_ZMK_RGB"));
        assert!(!conf.contains("CONFIG_ZMK_POINTING"));
        assert!(!conf.contains("CONFIG_EC11"));
    }
}
