pub mod parse;

use std::collections::HashSet;
use std::fmt::Write as _;

use crate::codes;
use crate::ir::{Key, Keymap, MacroStep, TriLayer};

#[must_use] pub fn render(keymap: &Keymap, cols: Option<usize>) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by qmk2zmk\n");
    out.push_str("// Review and adjust before flashing\n\n");

    out.push_str("#include <behaviors.dtsi>\n");
    out.push_str("#include <dt-bindings/zmk/keys.h>\n");

    if uses_rgb(keymap) {
        out.push_str("#include <dt-bindings/zmk/rgb.h>\n");
    }
    if uses_mouse(keymap) {
        out.push_str("#include <dt-bindings/zmk/mouse.h>\n");
    }

    out.push_str("\n/ {\n");

    if let Some(tri) = &keymap.tri_layer {
        render_conditional_layers(&mut out, tri);
    }

    if has_macros(keymap) {
        render_macros(&mut out, keymap);
    }

    render_keymap(&mut out, keymap, cols);

    out.push_str("};\n");
    out
}

fn render_conditional_layers(out: &mut String, tri: &TriLayer) {
    out.push_str("    conditional_layers {\n");
    out.push_str("        compatible = \"zmk,conditional-layers\";\n");
    out.push_str("        tri_layer {\n");
    let _ = writeln!(out, "            if-layers = <{} {}>;", tri.lower, tri.upper);
    let _ = writeln!(out, "            then-layer = <{}>;", tri.tri);
    out.push_str("        };\n");
    out.push_str("    };\n\n");
}

fn render_macros(out: &mut String, keymap: &Keymap) {
    out.push_str("    macros {\n");

    // Emit fully defined macros
    for m in &keymap.macros {
        let _ = writeln!(out, "        {}: {} {{", m.name, m.name);
        out.push_str("            compatible = \"zmk,behavior-macro\";\n");
        out.push_str("            #binding-cells = <0>;\n");
        if m.steps.is_empty() {
            out.push_str("            // TODO: fill in macro steps\n");
            out.push_str("            bindings = <&none>;\n");
        } else {
            let steps: Vec<String> = m
                .steps
                .iter()
                .map(|s| match s {
                    MacroStep::Tap(k) => format!("<&kp {k}>"),
                    MacroStep::Wait(ms) => format!("<&macro_wait_time {ms}>"),
                })
                .collect();
            let _ = writeln!(out, "            bindings = {};", steps.join(", "));
        }
        out.push_str("        };\n");
    }

    // Emit stubs for referenced macros that weren't fully parsed
    let defined: HashSet<_> = keymap.macros.iter().map(|m| m.name.as_str()).collect();
    let mut seen: HashSet<String> = HashSet::new();
    for layer in &keymap.layers {
        for key in &layer.keys {
            let Key::Macro(name) = key else { continue };
            if !defined.contains(name.as_str()) && seen.insert(name.clone()) {
                let _ = writeln!(out, "        {name}: {name} {{");
                out.push_str("            compatible = \"zmk,behavior-macro\";\n");
                out.push_str("            #binding-cells = <0>;\n");
                out.push_str("            // TODO: fill in macro steps\n");
                out.push_str("            bindings = <&none>;\n");
                out.push_str("        };\n");
            }
        }
    }

    out.push_str("    };\n\n");
}

fn render_keymap(out: &mut String, keymap: &Keymap, cols_override: Option<usize>) {
    out.push_str("    keymap {\n");
    out.push_str("        compatible = \"zmk,keymap\";\n\n");

    let cols = infer_cols(keymap, cols_override);

    for layer in &keymap.layers {
        let label = layer_label(&layer.name);
        let _ = writeln!(out, "        {label} {{");
        out.push_str("            bindings = <\n");

        // Compute column width for alignment, ignoring TODO comments
        let rendered: Vec<String> = layer.keys.iter().map(render_key).collect();
        let col_width = rendered
            .iter()
            .filter(|s| !s.starts_with("/*"))
            .map(std::string::String::len)
            .max()
            .unwrap_or(6)
            .min(28)
            + 1;

        for (i, binding) in rendered.iter().enumerate() {
            if i % cols == 0 {
                out.push_str("               ");
            }
            let _ = write!(out, "{binding:<col_width$}");
            if (i + 1) % cols == 0 || i + 1 == rendered.len() {
                out.push('\n');
            }
        }

        out.push_str("            >;\n");
        out.push_str("        };\n\n");
    }

    out.push_str("    };\n");
}

fn render_key(key: &Key) -> String {
    match key {
        Key::Kp(k)        => format!("&kp {k}"),
        Key::Mo(n)        => format!("&mo {n}"),
        Key::Lt(n, k)     => format!("&lt {n} {k}"),
        Key::Mt(m, k)     => format!("&mt {m} {k}"),
        Key::Tog(n)       => format!("&tog {n}"),
        Key::Sk(m)        => format!("&sk {m}"),
        Key::Sl(n)        => format!("&sl {n}"),
        Key::To(n) | Key::Df(n) => format!("&to {n}"),
        Key::Mmv(d)       => format!("&mmv {d}"),
        Key::Mkp(b)       => format!("&mkp {b}"),
        Key::Msc(d)       => format!("&msc {d}"),
        Key::Trans        => "&trans".into(),
        Key::None         => "&none".into(),
        Key::CapsWord     => "&caps_word".into(),
        Key::Bootloader   => "&bootloader".into(),
        Key::SysReset     => "&sys_reset".into(),
        Key::RgbUg(a)     => format!("&rgb_ug {a}"),
        Key::Macro(name)  => format!("&{name}"),
        Key::Unknown(s)   => format!("/* TODO: {s} */"),
    }
}

fn layer_label(name: &str) -> String {
    let base = name
        .trim_start_matches('_')
        .trim_end_matches("_layer")
        .to_lowercase();
    if base.is_empty() { "default_layer".into() } else { format!("{base}_layer") }
}

fn infer_cols(keymap: &Keymap, override_cols: Option<usize>) -> usize {
    if let Some(n) = override_cols { return n; }
    if let Some(layout) = &keymap.layout
        && let Some(n) = codes::keyboard_cols(layout)
    {
        return n;
    }
    for &cols in &[12usize, 10, 6] {
        if keymap.layers.first().is_some_and(|l| l.keys.len() % cols == 0) {
            return cols;
        }
    }
    12
}

fn uses_rgb(keymap: &Keymap) -> bool {
    keymap
        .layers
        .iter()
        .flat_map(|l| &l.keys)
        .any(|k| matches!(k, Key::RgbUg(_)))
}

fn uses_mouse(keymap: &Keymap) -> bool {
    keymap
        .layers
        .iter()
        .flat_map(|l| &l.keys)
        .any(|k| matches!(k, Key::Mmv(_) | Key::Mkp(_) | Key::Msc(_)))
}

fn has_macros(keymap: &Keymap) -> bool {
    !keymap.macros.is_empty()
        || keymap
            .layers
            .iter()
            .flat_map(|l| &l.keys)
            .any(|k| matches!(k, Key::Macro(_)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::Layer;

    fn simple_keymap(keys: Vec<Key>) -> Keymap {
        Keymap {
            keyboard: None,
            layout: None,
            layers: vec![Layer { name: "_BASE".into(), index: 0, keys }],
            macros: vec![],
            tri_layer: None,
        }
    }

    #[test]
    fn render_key_basic() {
        assert_eq!(render_key(&Key::Kp("TAB".into())),  "&kp TAB");
        assert_eq!(render_key(&Key::Trans),              "&trans");
        assert_eq!(render_key(&Key::None),               "&none");
        assert_eq!(render_key(&Key::CapsWord),           "&caps_word");
        assert_eq!(render_key(&Key::Bootloader),         "&bootloader");
        assert_eq!(render_key(&Key::SysReset),           "&sys_reset");
    }

    #[test]
    fn render_key_behaviors() {
        assert_eq!(render_key(&Key::Mo(1)),                    "&mo 1");
        assert_eq!(render_key(&Key::Tog(2)),                   "&tog 2");
        assert_eq!(render_key(&Key::Sk("LSHFT".into())),       "&sk LSHFT");
        assert_eq!(render_key(&Key::Sl(1)),                    "&sl 1");
        assert_eq!(render_key(&Key::To(0)),                    "&to 0");
        assert_eq!(render_key(&Key::Df(1)),                    "&to 1");
        assert_eq!(render_key(&Key::Mmv("MOVE_UP".into())),    "&mmv MOVE_UP");
        assert_eq!(render_key(&Key::Mkp("LCLK".into())),       "&mkp LCLK");
        assert_eq!(render_key(&Key::Msc("SCRL_UP".into())),    "&msc SCRL_UP");
        assert_eq!(render_key(&Key::Mt("LALT".into(), "Z".into())), "&mt LALT Z");
        assert_eq!(render_key(&Key::Lt(1, "SPACE".into())),    "&lt 1 SPACE");
        assert_eq!(render_key(&Key::RgbUg("RGB_TOG".into())),  "&rgb_ug RGB_TOG");
        assert_eq!(render_key(&Key::Macro("MY_MACRO".into())), "&MY_MACRO");
    }

    #[test]
    fn mouse_include_only_when_needed() {
        let without = simple_keymap(vec![Key::Kp("A".into())]);
        assert!(!render(&without, None).contains("zmk/mouse.h"));

        let with_mmv = simple_keymap(vec![Key::Mmv("MOVE_UP".into())]);
        assert!(render(&with_mmv, None).contains("zmk/mouse.h"));

        let with_mkp = simple_keymap(vec![Key::Mkp("LCLK".into())]);
        assert!(render(&with_mkp, None).contains("zmk/mouse.h"));
    }

    #[test]
    fn render_key_unknown() {
        let out = render_key(&Key::Unknown("WEIRD_KEY".into()));
        assert!(out.contains("WEIRD_KEY"));
        assert!(out.starts_with("/*"));
    }

    #[test]
    fn layer_label_strips_underscore() {
        assert_eq!(layer_label("_BASE"),   "base_layer");
        assert_eq!(layer_label("_LOWER"),  "lower_layer");
        assert_eq!(layer_label("_ADJUST"), "adjust_layer");
        assert_eq!(layer_label("QWERTY"),  "qwerty_layer");
        assert_eq!(layer_label(""),        "default_layer");
        // Round-trip: names already ending in _layer should not double it
        assert_eq!(layer_label("base_layer"),   "base_layer");
        assert_eq!(layer_label("lower_layer"),  "lower_layer");
        assert_eq!(layer_label("adjust_layer"), "adjust_layer");
    }

    #[test]
    fn output_includes_zmk_header() {
        let km = simple_keymap(vec![Key::Kp("A".into())]);
        let out = render(&km, None);
        assert!(out.contains("#include <behaviors.dtsi>"));
        assert!(out.contains("#include <dt-bindings/zmk/keys.h>"));
    }

    #[test]
    fn rgb_include_only_when_needed() {
        let without_rgb = simple_keymap(vec![Key::Kp("A".into())]);
        assert!(!render(&without_rgb, None).contains("zmk/rgb.h"));

        let with_rgb = simple_keymap(vec![Key::RgbUg("RGB_TOG".into())]);
        assert!(render(&with_rgb, None).contains("zmk/rgb.h"));
    }

    #[test]
    fn conditional_layers_block_emitted() {
        let mut km = simple_keymap(vec![Key::Trans]);
        km.tri_layer = Some(TriLayer { lower: 1, upper: 2, tri: 3 });
        let out = render(&km, None);
        assert!(out.contains("conditional_layers"));
        assert!(out.contains("if-layers = <1 2>"));
        assert!(out.contains("then-layer = <3>"));
    }

    #[test]
    fn macro_stub_emitted_for_referenced_macro() {
        let km = simple_keymap(vec![Key::Macro("MY_MACRO".into())]);
        let out = render(&km, None);
        assert!(out.contains("MY_MACRO: MY_MACRO"));
        assert!(out.contains("zmk,behavior-macro"));
        assert!(out.contains("TODO"));
    }

    #[test]
    fn no_macros_block_when_unused() {
        let km = simple_keymap(vec![Key::Kp("A".into()), Key::Trans]);
        let out = render(&km, None);
        assert!(!out.contains("macros {"));
    }

    #[test]
    fn layer_bindings_present() {
        let km = simple_keymap(vec![Key::Kp("TAB".into()), Key::Trans, Key::Mo(1)]);
        let out = render(&km, None);
        assert!(out.contains("base_layer"));
        assert!(out.contains("bindings = <"));
        assert!(out.contains("&kp TAB"));
        assert!(out.contains("&trans"));
        assert!(out.contains("&mo 1"));
    }

    #[test]
    fn infer_cols_from_layout_name() {
        let mut km = simple_keymap(vec![Key::Trans; 48]);
        km.layout = Some("LAYOUT_planck_grid".into());
        assert_eq!(infer_cols(&km, None), 12);

        km.layout = Some("LAYOUT_crkbd_base".into());
        assert_eq!(infer_cols(&km, None), 6);
    }
}
