use std::collections::HashSet;

use crate::ir::*;

pub fn render(keymap: &Keymap) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by qmk2zmk\n");
    out.push_str("// Review and adjust before flashing\n\n");

    out.push_str("#include <behaviors.dtsi>\n");
    out.push_str("#include <dt-bindings/zmk/keys.h>\n");

    if uses_rgb(keymap) {
        out.push_str("#include <dt-bindings/zmk/rgb.h>\n");
    }

    out.push_str("\n/ {\n");

    if let Some(tri) = &keymap.tri_layer {
        render_conditional_layers(&mut out, tri);
    }

    if has_macros(keymap) {
        render_macros(&mut out, keymap);
    }

    render_keymap(&mut out, keymap);

    out.push_str("};\n");
    out
}

fn render_conditional_layers(out: &mut String, tri: &TriLayer) {
    out.push_str("    conditional_layers {\n");
    out.push_str("        compatible = \"zmk,conditional-layers\";\n");
    out.push_str("        tri_layer {\n");
    out.push_str(&format!(
        "            if-layers = <{} {}>;\n",
        tri.lower, tri.upper
    ));
    out.push_str(&format!("            then-layer = <{}>;\n", tri.tri));
    out.push_str("        };\n");
    out.push_str("    };\n\n");
}

fn render_macros(out: &mut String, keymap: &Keymap) {
    out.push_str("    macros {\n");

    // Emit fully defined macros
    for m in &keymap.macros {
        out.push_str(&format!("        {}: {} {{\n", m.name, m.name));
        out.push_str("            compatible = \"zmk,behavior-macro\";\n");
        out.push_str("            #binding-cells = <0>;\n");
        let steps: Vec<String> = m
            .steps
            .iter()
            .map(|s| match s {
                MacroStep::Tap(k) => format!("<&kp {}>", k),
                MacroStep::Wait(ms) => format!("<&macro_wait_time {}>", ms),
            })
            .collect();
        out.push_str(&format!("            bindings = {};\n", steps.join(", ")));
        out.push_str("        };\n");
    }

    // Emit stubs for referenced macros that weren't fully parsed
    let defined: HashSet<_> = keymap.macros.iter().map(|m| m.name.as_str()).collect();
    let mut seen: HashSet<String> = HashSet::new();
    for layer in &keymap.layers {
        for key in &layer.keys {
            if let Key::Macro(name) = key {
                if !defined.contains(name.as_str()) && seen.insert(name.clone()) {
                    out.push_str(&format!("        {}: {} {{\n", name, name));
                    out.push_str("            compatible = \"zmk,behavior-macro\";\n");
                    out.push_str("            #binding-cells = <0>;\n");
                    out.push_str("            // TODO: fill in macro steps\n");
                    out.push_str("            bindings = <&none>;\n");
                    out.push_str("        };\n");
                }
            }
        }
    }

    out.push_str("    };\n\n");
}

fn render_keymap(out: &mut String, keymap: &Keymap) {
    out.push_str("    keymap {\n");
    out.push_str("        compatible = \"zmk,keymap\";\n\n");

    let cols = infer_cols(keymap);

    for layer in &keymap.layers {
        let label = layer_label(&layer.name);
        out.push_str(&format!("        {} {{\n", label));
        out.push_str("            bindings = <\n");

        // Compute column width for alignment, ignoring TODO comments
        let rendered: Vec<String> = layer.keys.iter().map(render_key).collect();
        let col_width = rendered
            .iter()
            .filter(|s| !s.starts_with("/*"))
            .map(|s| s.len())
            .max()
            .unwrap_or(6)
            .min(28)
            + 1;

        for (i, binding) in rendered.iter().enumerate() {
            if i % cols == 0 {
                out.push_str("               ");
            }
            out.push_str(&format!("{:<width$}", binding, width = col_width));
            if (i + 1) % cols == 0 || i + 1 == rendered.len() {
                out.push('\n');
            }
        }

        out.push_str("            >;\n");
        out.push_str("        };\n\n");
    }

    out.push_str("    };\n");
}

fn render_key(key: &Key) -> String {
    match key {
        Key::Kp(k)        => format!("&kp {}", k),
        Key::Mo(n)        => format!("&mo {}", n),
        Key::Lt(n, k)     => format!("&lt {} {}", n, k),
        Key::Mt(m, k)     => format!("&mt {} {}", m, k),
        Key::Tog(n)       => format!("&tog {}", n),
        Key::Trans        => "&trans".into(),
        Key::None         => "&none".into(),
        Key::CapsWord     => "&caps_word".into(),
        Key::Bootloader   => "&bootloader".into(),
        Key::SysReset     => "&sys_reset".into(),
        Key::RgbUg(a)     => format!("&rgb_ug {}", a),
        Key::Macro(name)  => format!("&{}", name),
        Key::Unknown(s)   => format!("/* TODO: {} */", s),
    }
}

fn layer_label(name: &str) -> String {
    let base = name.trim_start_matches('_').to_lowercase();
    if base.is_empty() { "default_layer".into() } else { format!("{}_layer", base) }
}

fn infer_cols(keymap: &Keymap) -> usize {
    if let Some(layout) = &keymap.layout {
        let l = layout.to_lowercase();
        if l.contains("planck") || l.contains("preonic") {
            return 12;
        }
        if l.contains("crkbd") || l.contains("corne") {
            return 6;
        }
        if l.contains("kyria") || l.contains("lily58") {
            return 7;
        }
    }
    // Guess from key count: try 12, then 10, then 6
    for &cols in &[12usize, 10, 6] {
        if let Some(layer) = keymap.layers.first() {
            if layer.keys.len() % cols == 0 {
                return cols;
            }
        }
    }
    12
}

fn uses_rgb(keymap: &Keymap) -> bool {
    keymap
        .layers
        .iter()
        .flat_map(|l| &l.keys)
        .any(|k| matches!(k, Key::RgbUg(_)))
}

fn has_macros(keymap: &Keymap) -> bool {
    !keymap.macros.is_empty()
        || keymap
            .layers
            .iter()
            .flat_map(|l| &l.keys)
            .any(|k| matches!(k, Key::Macro(_)))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn simple_keymap(keys: Vec<Key>) -> Keymap {
        Keymap {
            keyboard: None,
            layout: None,
            layers: vec![Layer { name: "_BASE".into(), index: 0, keys }],
            macros: vec![],
            tri_layer: None,
        }
    }

    #[test]
    fn render_key_basic() {
        assert_eq!(render_key(&Key::Kp("TAB".into())),  "&kp TAB");
        assert_eq!(render_key(&Key::Trans),              "&trans");
        assert_eq!(render_key(&Key::None),               "&none");
        assert_eq!(render_key(&Key::CapsWord),           "&caps_word");
        assert_eq!(render_key(&Key::Bootloader),         "&bootloader");
        assert_eq!(render_key(&Key::SysReset),           "&sys_reset");
    }

    #[test]
    fn render_key_behaviors() {
        assert_eq!(render_key(&Key::Mo(1)),                    "&mo 1");
        assert_eq!(render_key(&Key::Tog(2)),                   "&tog 2");
        assert_eq!(render_key(&Key::Mt("LALT".into(), "Z".into())), "&mt LALT Z");
        assert_eq!(render_key(&Key::Lt(1, "SPACE".into())),    "&lt 1 SPACE");
        assert_eq!(render_key(&Key::RgbUg("RGB_TOG".into())),  "&rgb_ug RGB_TOG");
        assert_eq!(render_key(&Key::Macro("MY_MACRO".into())), "&MY_MACRO");
    }

    #[test]
    fn render_key_unknown() {
        let out = render_key(&Key::Unknown("WEIRD_KEY".into()));
        assert!(out.contains("WEIRD_KEY"));
        assert!(out.starts_with("/*"));
    }

    #[test]
    fn layer_label_strips_underscore() {
        assert_eq!(layer_label("_BASE"),   "base_layer");
        assert_eq!(layer_label("_LOWER"),  "lower_layer");
        assert_eq!(layer_label("_ADJUST"), "adjust_layer");
        assert_eq!(layer_label("QWERTY"),  "qwerty_layer");
        assert_eq!(layer_label(""),        "default_layer");
    }

    #[test]
    fn output_includes_zmk_header() {
        let km = simple_keymap(vec![Key::Kp("A".into())]);
        let out = render(&km);
        assert!(out.contains("#include <behaviors.dtsi>"));
        assert!(out.contains("#include <dt-bindings/zmk/keys.h>"));
    }

    #[test]
    fn rgb_include_only_when_needed() {
        let without_rgb = simple_keymap(vec![Key::Kp("A".into())]);
        assert!(!render(&without_rgb).contains("zmk/rgb.h"));

        let with_rgb = simple_keymap(vec![Key::RgbUg("RGB_TOG".into())]);
        assert!(render(&with_rgb).contains("zmk/rgb.h"));
    }

    #[test]
    fn conditional_layers_block_emitted() {
        let mut km = simple_keymap(vec![Key::Trans]);
        km.tri_layer = Some(TriLayer { lower: 1, upper: 2, tri: 3 });
        let out = render(&km);
        assert!(out.contains("conditional_layers"));
        assert!(out.contains("if-layers = <1 2>"));
        assert!(out.contains("then-layer = <3>"));
    }

    #[test]
    fn macro_stub_emitted_for_referenced_macro() {
        let km = simple_keymap(vec![Key::Macro("MY_MACRO".into())]);
        let out = render(&km);
        assert!(out.contains("MY_MACRO: MY_MACRO"));
        assert!(out.contains("zmk,behavior-macro"));
        assert!(out.contains("TODO"));
    }

    #[test]
    fn no_macros_block_when_unused() {
        let km = simple_keymap(vec![Key::Kp("A".into()), Key::Trans]);
        let out = render(&km);
        assert!(!out.contains("macros {"));
    }

    #[test]
    fn layer_bindings_present() {
        let km = simple_keymap(vec![Key::Kp("TAB".into()), Key::Trans, Key::Mo(1)]);
        let out = render(&km);
        assert!(out.contains("base_layer"));
        assert!(out.contains("bindings = <"));
        assert!(out.contains("&kp TAB"));
        assert!(out.contains("&trans"));
        assert!(out.contains("&mo 1"));
    }

    #[test]
    fn infer_cols_from_layout_name() {
        let mut km = simple_keymap(vec![Key::Trans; 48]);
        km.layout = Some("LAYOUT_planck_grid".into());
        assert_eq!(infer_cols(&km), 12);

        km.layout = Some("LAYOUT_crkbd_base".into());
        assert_eq!(infer_cols(&km), 6);
    }
}
